#!/usr/bin/python
import os, sys, inspect,logging

shortcuts = {}

def loadCfgs(path):
    global shortcuts
    shortcut = open(os.path.join(path,'shortcut.cfg'),'r')
    for line in shortcut:
        if line.find('#') != 0:
            parts = line.rstrip().split("=")
            if len(parts) == 2:
                shortcuts[parts[0]] = parts[1]

def getRealCmd(cmd):
    global shortcuts
    if cmd in shortcuts:
        return shortcuts[cmd]
    else:
        return cmd

def doDefaultActions(cmd, modules):
    processed = False
    if cmd == "version":
        print "0.0.1"
        processed = True
    elif cmd == "help":
        showHelp(modules)
        processed = True
    return processed


def main():
    pwd = os.path.abspath(os.path.split(inspect.getfile( inspect.currentframe() ))[0])
    ppd = os.path.dirname(pwd)
    if ppd not in sys.path:
        sys.path.insert(0, ppd)
    # use this if you want to include modules from a subforder
    modules = os.path.abspath(os.path.join(os.path.realpath(pwd),"modules"))
    if modules not in sys.path:
        sys.path.insert(0, modules)
    loadCfgs(pwd)

    cmd = "help" if len(sys.argv) < 2 else getRealCmd(sys.argv[1])

    try:
        method = sys.argv[2]
    except:
        method = "help"

    try:
        module = __import__(cmd)
        try:
            func = getattr(module, method)
            func(*sys.argv[3:]) # or func()
        except:
            module.process(*sys.argv[2:])
    except:
        logging.exception("This is embarassing, module %s failed to run."%(cmd))

main()
